# Workflow for testing CoDar.

name: tests

on:
  pull_request:
  push:
    branches: main

env:
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0  # SonarCloud prefers non-shallow clones
      - uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3.4.1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Run tests
        run: mvn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}